export const GET_CITY_REQUEST = 'GET_CITY_REQUEST';
export const GET_CITY_RESPONSE = 'GET_CITY_RESPONSE';
export const GET_CITY_FAILED = 'GET_CITY_FAILED';
export const GET_CITY_ENABLE_LOADER = 'GET_CITY_ENABLE_LOADER';
export const GET_CITY_DISABLE_LOADER = 'GET_CITY_DISABLE_LOADER';

export const GET_CURRENT_TEMP_REQUEST = 'GET_CURRENT_TEMP_REQUEST';
export const GET_CURRENT_TEMP_RESPONSE = 'GET_CURRENT_TEMP_RESPONSE';
export const GET_CURRENT_TEMP_FAILED = 'GET_CURRENT_TEMP_FAILED';
export const GET_CURRENT_TEMP_ENABLE_LOADER = 'GET_CURRENT_TEMP_ENABLE_LOADER';
export const GET_CURRENT_TEMP_DISABLE_LOADER = 'GET_CURRENT_TEMP_DISABLE_LOADER';