export const GET_CITY_REQUEST = 'GET_CITY_REQUEST';
export const GET_CITY_RESPONSE = 'GET_CITY_RESPONSE';
export const GET_CITY_FAILED = 'GET_CITY_FAILED';
export const GET_CITY_ENABLE_LOADER = 'GET_CITY_ENABLE_LOADER';
export const GET_CITY_DISABLE_LOADER = 'GET_CITY_DISABLE_LOADER';